imports:
    - { resource: "@SetonoSyliusKlaviyoPlugin/Resources/config/grids/setono_sylius_klaviyo_admin_member_list.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_klaviyo.command_bus: ~
